---
name: KygekPingTPS
version: 1.0.0
main: Kygekraqmak\KygekPingTPS\Main
api: 3.0.0
author: Kygekraqmak

commands:
  ping:
    description: Current ping of a player
    permission: kygekpingtps.ping
    usage: "/ping [player]"
  tps:
    description: Current TPS of the server
    permission: kygekpingtps.tps
    usage: "/tps"

permissions:
  kygekpingtps.ping:
    description: Permission to use /ping
    default: op
  kygekpingtps.tps:
    description: Permission to use /tps
    default: op
...
