---
#
#  PLUGIN BY:
#   _    __                  _                                     _
#  | |  / /                 | |                                   | |
#  | | / /                  | |                                   | |
#  | |/ / _   _  ____   ____| | ______ ____   _____ ______   ____ | | __
#  | |\ \| | | |/ __ \ / __ \ |/ /  __/ __ \ / __  | _  _ \ / __ \| |/ /
#  | | \ \ \_| | <__> |  ___/   <| / | <__> | <__| | |\ |\ | <__> |   <
#  |_|  \_\__  |\___  |\____|_|\_\_|  \____^_\___  |_||_||_|\____^_\|\_\
#            | |    | |                          | |
#         ___/ | ___/ |                          | |
#        |____/ |____/                           |_|
#
# KygekPingTPS configuration file
#

# Whether to check for plugin updates (Recommended)
check-updates: true

##### DANGER ZONE #####
# Do not change this (Only for internal use)!
config-version: "1.0"
#######################
...